const fs = require('node:fs/promises');
const { chromium } = require('playwright');
const base = process.env.PORTFOLIO_BASE_URL || 'http://127.0.0.1:5173';
let browser;
(async () => {
  await fs.mkdir('artifacts', { recursive: true });
  browser = await chromium.launch({ headless: true, channel: 'chrome' });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, locale: 'en-US' });
  await page.goto(base, { waitUntil: 'networkidle' });
  await page.waitForTimeout(800);
  await page.screenshot({ path: 'artifacts/hero.png' });
  const at = async position => {
    await page.evaluate(value => {
      const el = document.querySelector('#journey');
      window.scrollTo({ top: el.getBoundingClientRect().top + scrollY + value * (el.offsetHeight - innerHeight) / el.dataset.path.split(',').length, behavior: 'instant' });
    }, position);
    await page.waitForTimeout(700);
  };
  await at(.35);
  await page.screenshot({ path: 'artifacts/journey-desktop.png' });
  await at(.85);
  await page.screenshot({ path: 'artifacts/journey-transition.png' });
  await at(.35);
  await page.locator('[data-scene="dfriend"] [data-branch="seventeen"]').click();
  await page.waitForTimeout(1000);
  await page.screenshot({ path: 'artifacts/journey-branch.png' });
  await page.locator('[data-scene="seventeen"] [data-detail]').click();
  await page.screenshot({ path: 'artifacts/journey-reader.png' });
  await page.keyboard.press('Escape');
  await page.locator('.header-tools .language-toggle button').filter({ hasText: 'VI' }).click();
  await page.locator('.theme-toggle').click();
  await at(4.4);
  await page.screenshot({ path: 'artifacts/journey-vi-light.png' });
  await page.locator('[data-scene="research"] [data-detail]').click();
  await page.screenshot({ path: 'artifacts/reader-vi-light.png' });
  await page.keyboard.press('Escape');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(base, { waitUntil: 'networkidle' });
  await page.waitForTimeout(700);
  await page.screenshot({ path: 'artifacts/hero-mobile-vi-light.png' });
  await at(.65);
  await page.screenshot({ path: 'artifacts/journey-mobile-vi-light.png' });
  await page.locator('.theme-toggle').click();
  await page.locator('.header-tools .language-toggle button').filter({ hasText: 'EN' }).click();
  await at(.35);
  await page.screenshot({ path: 'artifacts/journey-mobile.png' });
  await page.locator('#contact').scrollIntoViewIfNeeded();
  await page.waitForTimeout(700);
  await page.screenshot({ path: 'artifacts/contact-mobile.png' });
  console.log('Captured desktop, transition, branch, popup, bilingual themes, mobile, and contact views.');
})().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => { await browser?.close(); });
