const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const { chromium } = require('playwright');
const { AxeBuilder } = require('@axe-core/playwright');
const base = process.env.PORTFOLIO_BASE_URL || 'http://127.0.0.1:4173';
let browser;
(async () => {
  browser = await chromium.launch({ channel:'chrome',headless:true });
  const context = await browser.newContext({viewport:{width:1440,height:900},locale:'en-US'});
  const page = await context.newPage();
  const errors=[];
  page.on('pageerror', e=>errors.push(e.message));
  await page.goto(base,{waitUntil:'networkidle'});
  await page.waitForTimeout(600);
  const pose = () => page.locator('.research-paper').evaluate(el=>{const m=new DOMMatrix(getComputedStyle(el).transform);return{y:m.m42,angle:Math.atan2(m.m12,m.m11)*180/Math.PI,scroll:scrollY};});
  const initial=await pose();
  await page.mouse.move(50,800);
  await page.mouse.wheel(0,120);
  await page.waitForTimeout(600);
  const wheel=await pose();
  assert.ok(wheel.y<-.1 && wheel.y>-5,'Small wheel input causes a gradual parallax displacement');
  assert.ok(wheel.angle<9,'Small wheel input no longer jumps to the final rotation');
  await page.mouse.wheel(0,180);
  await page.waitForTimeout(600);
  const scrollBase=await pose();
  const paperBox = await page.locator('.research-paper').boundingBox();
  await page.mouse.move(paperBox.x + paperBox.width / 2, Math.max(110, paperBox.y + paperBox.height * .7));
  await page.waitForTimeout(550);
  const hover=await pose();
  assert.ok(Math.abs(hover.y-(scrollBase.y-8))<.2,`Hover adds lift to current scroll position: ${JSON.stringify({scrollBase,hover})}`);
  await page.mouse.move(50,800);
  await page.waitForTimeout(550);
  const restored=await pose();
  assert.ok(Math.abs(restored.y-scrollBase.y)<.2,'Hover returns to the current parallax position');
  assert.ok(Math.abs(restored.angle-scrollBase.angle)<.1,'Hover returns to the current rotation');
  await page.keyboard.press('Tab');
  await page.locator('.research-paper').focus();
  await page.waitForTimeout(550);
  assert.equal(await page.locator('.research-paper').evaluate(el=>el.matches(':focus-visible')),true);
  const keyboardPose=await pose();
  await page.evaluate(()=>document.activeElement.blur());
  await page.waitForTimeout(550);
  const blurredPose=await pose();
  assert.ok(keyboardPose.y<blurredPose.y-7,'Keyboard focus supplies lift at its current scroll position');

  await page.locator('.folder').click();
  await page.waitForFunction(()=>document.querySelector('#journey').dataset.current==='dfriend');
  await page.waitForTimeout(1200);
  const sceneLink=page.locator('[data-scene="dfriend"] .scene-site');
  assert.equal(await sceneLink.getAttribute('href'),'https://www.dfriend.online/');
  assert.equal(await sceneLink.getAttribute('target'),'_blank');
  assert.equal(await sceneLink.getAttribute('rel'),'noopener noreferrer');
  assert.equal(await sceneLink.isVisible(),true);
  await page.locator('[data-scene="dfriend"] [data-detail]').click();
  const readerLink=page.locator('.reader-project-link');
  assert.equal(await readerLink.getAttribute('href'),'https://www.dfriend.online/');
  assert.equal(await readerLink.innerText(),'Visit D-Friend');
  await page.locator('.reader .language-toggle button').filter({hasText:'VI'}).click();
  assert.equal(await readerLink.innerText(),'Ghé D-Friend');
  const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
  assert.deepEqual(audit.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})),[]);
  await page.keyboard.press('Escape');
  await page.waitForFunction(()=>!document.querySelector('dialog').open);

  for(const width of [320,390,600,768,900,1024,1440]) {
    await page.setViewportSize({width,height:width<600?844:900});
    await page.goto(base,{waitUntil:'networkidle'});
    await page.evaluate(()=>window.scrollTo({top:180,behavior:'instant'}));
    await page.waitForTimeout(600);
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Desk overflow at ${width}`);
    if(width===390) {
      await page.locator('.folder').click();
      await page.waitForTimeout(1200);
      const linkBox=await page.locator('.scene-site').boundingBox();
      assert.ok(linkBox.x>=0 && linkBox.x+linkBox.width<=390,'Mobile product link fits');
      await page.screenshot({path:'artifacts/dfriend-link-mobile.png'});
    }
  }
  const reduced=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'});
  await reduced.goto(base,{waitUntil:'networkidle'});
  const read=()=>reduced.locator('.research-paper').evaluate(el=>getComputedStyle(el).transform);
  const staticTransform=await read();
  await reduced.mouse.wheel(0,180);
  await reduced.locator('.research-paper').hover();
  await reduced.waitForTimeout(500);
  assert.equal(await read(),staticTransform,'Reduced motion stays static');
  assert.deepEqual(errors,[]);
  const report={passed:true,base,executedAt:new Date().toISOString(),initial,wheel,scrollBase,hover,restored,checks:['Gradual desk parallax','Hover/scroll composition and keyboard focus','Bilingual external product links','Reader Axe accessibility','Seven viewport widths','Reduced motion']};
  await fs.mkdir('artifacts',{recursive:true});
  await fs.writeFile('artifacts/desk-verification.json',JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();});
